### ISSUE TITLE
pure-exporter - [CRITICAL] WORKER TIMEOUT

### ISSUE THREAD

**Issue by gopherunner** [PureStorage-OpenConnect/pure-exporter#38]
Hi, I'm having some issues while trying to run the (pure-exporter) container:

genegatpure/pure-exporter   "gunicorn pure_expor…"   18 minutes ago   Up 9 minutes   0.0.0.0:9491->9491/tcp, :::9491->9491/tcp   pure-exporter

And the problem is that Prometheus is not logging any metrics from the arrays.

# docker logs pure-exporter
[2021-06-02 21:48:28 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-06-02 21:48:28 +0000] [1] [INFO] Listening at: http://0.0.0.0:9491 (1)
[2021-06-02 21:48:28 +0000] [1] [INFO] Using worker: sync
[2021-06-02 21:48:28 +0000] [7] [INFO] Booting worker with pid: 7
[2021-06-02 21:48:28 +0000] [8] [INFO] Booting worker with pid: 8
[2021-06-02 21:57:45 +0000] [1] [INFO] Handling signal: term
[2021-06-02 21:57:45 +0000] [8] [INFO] Worker exiting (pid: 8)
[2021-06-02 21:57:45 +0000] [7] [INFO] Worker exiting (pid: 7)
[2021-06-02 21:57:45 +0000] [1] [INFO] Shutting down: Master
[2021-06-02 21:57:55 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-06-02 21:57:55 +0000] [1] [INFO] Listening at: http://0.0.0.0:9491 (1)
[2021-06-02 21:57:55 +0000] [1] [INFO] Using worker: sync
[2021-06-02 21:57:55 +0000] [7] [INFO] Booting worker with pid: 7
[2021-06-02 21:57:55 +0000] [8] [INFO] Booting worker with pid: 8
[2021-06-02 21:58:40 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
...
[2021-06-02 22:04:05 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:21)
[2021-06-02 22:04:05 +0000] [21] [INFO] Worker exiting (pid: 21)
[2021-06-02 22:04:05 +0000] [23] [INFO] Booting worker with pid: 23
[2021-06-02 22:04:35 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:22)
[2021-06-02 22:04:35 +0000] [22] [INFO] Worker exiting (pid: 22)
[2021-06-02 22:04:35 +0000] [24] [INFO] Booting worker with pid: 24

Any ideas? Thanks in advance

**Comment by gopherunner** [comment]
Also It's rare since if I point to the following url I'm getting info from the arrays:

http://xx.xx.xx.xx:9491/metrics/flasharray?endpoint=xx.xx.xx.xx&apitoken=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

but when I prompt to prometheus url (http://xx.xx.xx.xx:9090/graph) i'm not seeing any data in there with 'pureXX'

**Comment by gopherunner** [comment]
[2021-06-02 22:45:22,540] ERROR in app: Exception on /metrics/flasharray [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/pure_exporter.py", line 135, in route_flasharray_all
    return route_flasharray('all')
  File "/app/pure_exporter.py", line 131, in route_flasharray
    return route_array('flasharray', m_type)
  File "/usr/local/lib/python3.9/site-packages/flask_httpauth.py", line 176, in decorated
    return f(*args, **kwargs)
  File "/app/pure_exporter.py", line 125, in route_array
    resp = make_response(generate_latest(registry), 200)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 177, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/registry.py", line 83, in collect
    for metric in collector.collect():
  File "/app/flasharray_collector/flasharray_collector.py", line 40, in collect
    yield from ArrayInfoMetrics(self.fa).get_metrics()
  File "/app/flasharray_collector/flasharray_metrics/array_info_metrics.py", line 24, in get_metrics
    self._info()
  File "/app/flasharray_collector/flasharray_metrics/array_info_metrics.py", line 14, in _info
    array = self.fa.get_array()
  File "/app/flasharray_collector/flasharray_metrics/flasharray.py", line 53, in get_array
    self.array = self.flasharray.get()
AttributeError: 'NoneType' object has no attribute 'get'
[02/Jun/2021:22:45:22 +0000] xx.xx.xx.xx /metrics/flasharray - 5 21

**Comment by gopherunner** [comment]
the docker-compose file is:

`version: '3'

services:
  prometheus:
      container_name: prometheus
      image: prom/prometheus:latest
      restart: always
      ports:
      - 9090:9090
      volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/pure.rules:/etc/prometheus/pure.rules
      - prometheus_data:/prometheus
      command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=5d

  prometheus-alertmanager:
    container_name: prometheus-alertmanager
    image: prom/alertmanager:latest
    restart: always
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml

  pure-exporter:
      container_name: pure-exporter
      image: genegatpure/pure-exporter
      restart: always
      ports:
      - 9491:9491

  grafana:
      container_name: grafana
      image: grafana/grafana:latest
      restart: always
      depends_on:
      - prometheus
      ports:
      - 3000:3000
      volumes:
      - ./grafana/plugins:/var/lib/grafana/plugins
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana

volumes:
    grafana_data:
      driver: local
      driver_opts:
        type: "nfs"
        o: "addr=<NFS-IP>,rw,noatime"
        device: ":/DB"
    prometheus_data:
      driver: local
      driver_opts:
        type: "nfs"
        o: "addr=<NFS-IP>,rw,noatime"
        device: ":/DB"
    alertmanager_data:
      driver: local
      driver_opts:
        type: "nfs"
        o: "addr=<NFS-IP>,rw,noatime"
        device: ":/DB"
`

**Comment by gopherunner** [comment]
and the prometheus.yml file:

```
global:
  scrape_interval:     1m # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15m # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 1m

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
#rule_files:
#   - 'alert.rules'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # Job for all Prometheus
  - job_name: 'prometheus'

    static_configs:
    - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']

# Job for all Pure Flasharrays
  - job_name: 'pure_flasharray'
    metrics_path: /metrics/flasharray
    relabel_configs:
    # meta label of target address --> get parameter "pure_host"
    - source_labels: [__address__]
      target_label: __param_endpoint
    # label of target api token --> get parameter "pure_apitoken"
    - source_labels: [__pure_apitoken]
      target_label: __param_apitoken
    # display the pure host as the instance label
    - source_labels: [__address__]
      target_label: instance
    # point the exporter to the scraping endpoint of the exporter
    - target_label: __address__
      replacement: localhost:9491

    static_configs:
    - targets: [ xx.xx.xx.xx ]
      labels:
        __pure_apitoken: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
        location: us
        site: siteA
        is_production: 1
```
