### ISSUE TITLE
Config file example not available

### ISSUE THREAD

**Issue by 6monlambert** [PureStorage-OpenConnect/pure-exporter#48]
Hello,

I am trying to configure the exporter, but am not able to make it work.
I am using the pure-exporter container (version 1.2.5-a).
This is my Prometheus configuration file : 

```
scrape_configs:
  - job_name: "pure-exporter"
    params:
      endpoint: ['array.domain.intra']
      #user: ['centreon']
      api_token: ['376db02f-249e-d056-ed91-a9df394aea48']
    metrics_path: '/metrics/flasharray'
    static_configs:
      - targets: ["localhost:9491"]
```

Both containers (pure-exporter and Prometheus) both starts correctly but I get an "Unauthorized access" when trying to access the exporter metrics.

The resulting URL is : http://localhost:9491/metrics/flasharray?api_token=376db02f-249e-d056-ed91-a9df394aea48&endpoint=array.domain.intra

The thing is, the specified token is created for the user 'centreon'. When I uncomment the line, the result is the same. 

The config directory (https://github.com/PureStorage-OpenConnect/pure-exporter/tree/master/config) being empty, I was not able to find a solution.

What am I missing here ? 
Simon
